name: File Structure Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate_integrity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run Validator
      run: python ./_checks/directory_structure/validate.py
