name: Markdown Linting Test

on:
  pull_request:
    branches:
      - master
      - uat_test_1
      - main
    paths:
      - '**.md'

jobs:
  mdl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install mdl gem
      run: gem install mdl
    - name: Run mdl
      run: mdl src/ --style=_checks/styles/style-rules-prod --ignore-front-matter --git-recurse -- .
