name: Metadata Validation
on: ['pull_request']

jobs:
  validate_integrity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out
      uses: actions/checkout@v2

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Validate
      run: deno run --allow-read --unstable _checks/metadata_validation/mod.ts
