name: Metadata Validation
on: ['pull_request']

jobs:
  metadata-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Cache dependencies
      run: deno cache --unstable _checks/metadata_validation/mod.ts
    - name: Validate article metadata
      run: deno run --allow-read _checks/metadata_validation/mod.ts
